# Generated by Django 4.1.5 on 2023-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parse_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_app",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="name_app code",
                    ),
                ),
                (
                    "name_company",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="name_company",
                    ),
                ),
                (
                    "release_year",
                    models.CharField(
                        blank=True,
                        max_length=400,
                        null=True,
                        verbose_name="release_year",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=400, null=True, verbose_name="email"
                    ),
                ),
            ],
        ),
    ]
