# Generated by Django 4.1.5 on 2023-01-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_parse_data_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parse_data",
            name="link",
            field=models.CharField(
                blank=True, max_length=700, null=True, verbose_name="link"
            ),
        ),
    ]
